CREATE IF NOT EXISTS DATABASE crossover_db;
USE crossover_db;

CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    email VARCHAR(85) NOT NULL UNIQUE,
    password VARCHAR(450) NOT NULL,
    profile TINYINT(1) NOT NULL DEFAULT 0,
);

